# fly.toml app configuration file generated for vivarium-gallery on 2026-04-07T14:18:11-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vivarium-gallery'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile'

[[mounts]]
  source = 'gallery_data'
  destination = '/srv/public'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  min_machines_running = 1

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpus = 1
  memory_mb = 256
